export enum ApplicationSummaryActions {
    ADD_APPLICATION_SUMMARY = 'ADD_APPLICATION_SUMMARY',
    FETCH_APPLICATION_EVENTS = 'FETCH_APPLICATION_EVENT',
    SET_APPLICATION_EVENTS = 'SET_APPLICATION_EVENTS'
};