export enum ChemicalApplicationActions {
    ADD_AREA_OF_APPLICATION = 'ADD_AREA_OF_APPLICATION',
    UPDATE_TARGET_PESTS = 'UPDATE_TARGET_PESTS',
    UPDATE_DATE_OF_APPLICATION = 'UPDATE_DATE_OF_APPLICATION',
    UPDATE_TOTAL_AREA_OF_APP = 'UPDATE_TOTAL_AREA_OF_APP',
    UPDATE_TOTAL_AREA_OF_APP_UNITS = 'UPDATE_TOTAL_AREA_OF_APP_UNITS',
}